POST http://localhost:4000/api-v1/register
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "nama": "Toko Jaya Abadi",
  "alamat": "JL Beringin raya I",
  "hp": "085761298781",
  "user": {
    "email": "darmawandoni6@gmail.com",
    "password": "kiasu123"
  }
}

POST http://localhost:4000/api-v1/login
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
    "email": "darmawandoni6@gmail.com",
    "password": "kiasu123"
}
GET http://localhost:4000/api-v1/profile
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

